### ISSUE TITLE
bash autocompletion not working with "auto_activate_base false"

### ISSUE THREAD

**Issue by omer-musa-battal** [tartansandal/mamba-bash-completion#1]
Some system info, if it would be helpful:

```
$ uname -a
Linux my-custom-machine-name 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I made a fresh `mambaforge` installation using the following commands:

```
bash Mambaforge-Linux-x86_64.sh

conda config --set auto_activate_base false
conda config --set channel_priority strict

conda update conda

diff <(conda list) <(mamba list)  # just to make sure the same package list is shown.
```

Note that I selected the `conda init bash` option during the installation, so I am not running it again.

Then I installed `mamba-bash-completion` using the following command:

```
conda install mamba-bash-completion
```

I also appended the following to my `~/.bash_aliases` file:

```
CONDA_ROOT="${MY_CUSTOM_DIR}/mambaforge"  # <- set to your Anaconda/Miniconda installation directory
if [[ -r "${CONDA_ROOT}/etc/profile.d/bash_completion.sh" ]]; then
	source "${CONDA_ROOT}/etc/profile.d/bash_completion.sh"
fi
```

Then I restarted my shell several times, but bash autocompletion did not work.
Activating and deactivating the base environment does not seem to change the result.

Am I doing something incorrectly? Or is mambaforge somehow not supported?

**Comment by omer-musa-battal** [comment]
After some trials, I have made the following observations:

After opening a new shell, If I do not try to use bash completion, and enter the following commands, then bash completion starts working for both `conda` and `mamba`.

```
conda activate
conda activate
```

or

```
mamba activate
mamba activate
```

i.e. activating the environment twice seems to make bash completion work somehow.

if I try to use bash completion while entering these commands, the behavior is kinda different.

runninng `conda activate` twice with bash completion trial results in conda bash completion not working initially.
however, mamba bash completion works, and after mamba bash completion works once, conda bash completion also works.

runninng `mamba activate` twice with bash completion trial  results in working conda bash completion.
mamba bash completion never works in this case.

for now, I have added the following commands to my `.bashrc` file, right under the `# <<< conda initialize <<<` line:

```
# temporary workaround for mamba bash completion.
mamba activate
mamba activate
mamba deactivate  # do not overwrite "conda config --set auto_activate_base false"
```

my `conda` and `mamba` bash completions are now working on every terminal, but the terminal startup slowed down as a result of my actions in `.bashrc` file.

**Comment by omer-musa-battal** [comment]
my issue seems to be similar to the following one:

tartansandal/conda-bash-completion#12

**Comment by tartansandal** [comment]
Hi @omer-musa-battal. Thanks for the bug report and the debugging notes. They are much appreciated :) I hope to get a chance to investigate over the next few days.

**Comment by tartansandal** [comment]
Hi @omer-musa-battal. I've just tried to replicate your installation process using docker and completion for both `conda` and `mamba` seemed to work.

The only difference for me was that I ran the `conda install mamba-bash-completion` command before setting `conda config --set auto_activate_base false`. I did it that way because it did not make sense to run an install without having an environment active. I'm wondering if this is what is causing your problem?

So which environment did `mamba-bash-completion` and its dependencies get installed into?  It should be `base`, but maybe the activate hooks did not get installed properly.

**Comment by tartansandal** [comment]
@omer-musa-battal also

In your `~/.bash_aliases` file, I'm assuming `${MY_CUSTOM_DIR}` is defined and points to the correct place?

Maybe put a temporary

```
echo "sourcing bash completion"
```

inside the conditional to check that that is actually being called.

**Comment by omer-musa-battal** [comment]
Hi @tartansandal,

I removed the `mambaforge` installation directory, the `~/.conda` directory and `~/.condarc` file.
I also reverted all changes related to conda in `~/.bashrc` and `~/.bash_aliases` files.
Essentially, I uninstalled `mambaforge` completely.

Afterwards, I reinstalled `mambaforge`, but did not use the following command this time:
```
conda config --set auto_activate_base false
```
I also did not made any manual modifications to my `~/.bashrc` and `~/.bash_aliases` files in this installation.

After restarting the terminal, the `base` environment is activated by default, and both `conda` and `mamba` bash completions work properly, as you said.

But once I enable the `--set auto_activate_base false` setting and restart the shell, bash completion stops working again. The workarounds I provided in my previous message apply this time too (i.e. double activation followed by a single deactivation).

The problem disappears again when `--set auto_activate_base true` is run once more, and restarting the shell.

In the end, it seems that the problem is with the following configuration:
```
conda config --set auto_activate_base false
```
When this setting is enabled, bash completion does not work properly.

**Comment by omer-musa-battal** [comment]
> @omer-musa-battal also
> 
> In your `~/.bash_aliases` file, I'm assuming `${MY_CUSTOM_DIR}` is defined and points to the correct place?
> 
> Maybe put a temporary
> 
> ```
> echo "sourcing bash completion"
> ```
> 
> inside the conditional to check that that is actually being called.

I completely removed these lines in my `.bash_aliases` file altogether, since it did not seem to make a change in the result anyway.
Result only changes with the `--set auto_activate_base false` configuration.

**Comment by tartansandal** [comment]
@omer-musa-battal Excellent! you've got the completion working. The only problem is activating it without having the `base` environment active. This is why the documentation suggested the lines that you put in your `~/.bash_aliases` file (they do the same thing as the `base` environment activation hooks. They should look something like:

```
CONDA_ROOT=~/mambaforge   # <- set to your Anaconda/Miniconda installation directory
if [[ -r $CONDA_ROOT/etc/profile.d/bash_completion.sh ]]; then
    # Comment out the following line once you've got completion working
    echo "Sourcing bash completion setup script"
    source $CONDA_ROOT/etc/profile.d/bash_completion.sh
fi
```

I've added an extra line for debugging. If you do not see "Sourcing bash completion setup script" when you start a new shell, then your path to CONDA_ROOT is incorrect.

**Comment by omer-musa-battal** [comment]
I do see "Sourcing bash completion setup script" line when I start a new shell, if I append my `~/.bash_aliases` file with your sugessted changes. When I run the following command on the opened shell, the file is seen to exist as well:
```
ls "${CONDA_ROOT}/etc/profile.d/bash_completion.sh"
```
So I do not think that my `CONDA_ROOT` path is incorrect.

I also modified the content of the `$CONDA_ROOT/etc/profile.d/bash_completion.sh` file to include an echo:
```
# ... contents omitted for brevity ...
        if shopt -q progcomp && [ -r /home/battal/all/sw/utils/mambaforge/share/bash-completion/bash_completion ]; then
            # Source completion code.
            echo "Sourcing bash completion for real"  # appended line
            . /home/battal/all/sw/utils/mambaforge/share/bash-completion/bash_completion
        fi
# ... contents omitted for brevity ...
```

(at this point, keeping my custom paths hidden seems to hinder progress, so I will not hide them anymore)

I am seeing these lines on new shells, after the above modification:
```
Sourcing bash completion setup script
Sourcing bash completion for real
```

Unfortunately, bash completion still does not work on these shells.

**Comment by tartansandal** [comment]
@omer-musa-battal I just want to check that you are hitting `<tab>` twice when you are trying to trigger completion. I've had reports that this can be required on some systems due to the way completion is auto-loaded.

Otherwise does running the following get completion working?

```
. /home/battal/all/sw/utils/mambaforge/share/bash-completion/completions/mamba
```

**Comment by tartansandal** [comment]
Also, note that on Linux systems with bash-completion already installed, the [manual installation method](https://github.com/tartansandal/conda-bash-completion#method-2-manually) might be more appropriate if you want to keep the `base` environment deactivated.

**Comment by omer-musa-battal** [comment]
> @omer-musa-battal I just want to check that you are hitting `<tab>` twice when you are trying to trigger completion. I've had reports that this can be required on some systems due to the way completion is auto-loaded.
> 
> Otherwise does running the following get completion working?
> 
> ```
> . /home/battal/all/sw/utils/mambaforge/share/bash-completion/completions/mamba
> ```

I am hitting `<tab>` multiple times in a row, and nothing happens.
Running the suggested command also did not change the result.

**Comment by omer-musa-battal** [comment]
> Also, note that on Linux systems with bash-completion already installed, the [manual installation method](https://github.com/tartansandal/conda-bash-completion#method-2-manually) might be more appropriate if you want to keep the `base` environment deactivated.

This seems to solve the issue after some modifications.

my new `~/.bash_aliases` file:
```
# Enable bash completion for custom programs.
for bc_file in ~/.bash_completion.d/* ; do
  [ -f "${bc_file}" ] && source "${bc_file}"
done

CONDA_ROOT="/home/battal/all/sw/utils/mambaforge"
```

Afterwards, I ran the following commands on a new shell:
```
mkdir -p "${HOME}/.bash_completion.d/"
cp "${CONDA_ROOT}/share/bash-completion/completions/conda" "${HOME}/.bash_completion.d/"
cp "${CONDA_ROOT}/share/bash-completion/completions/mamba" "${HOME}/.bash_completion.d/"
```

Then I restarted my shell, and bash completion finally worked without activating the conda environment.

**Comment by omer-musa-battal** [comment]
Thanks for your help @tartansandal, much appreciated.

However, I still do not understand why the direct `conda` method of installation did not work, and I had to resort to manual installation.
If it is not much trouble, could you explain the reason for this?

I generally try to avoid manual configurations in order to simplify reproducibility, that is why I would prefer the `conda` method over the manual method, if possible.

**Comment by tartansandal** [comment]
> Thanks for your help @tartansandal, much appreciated.

Not a problem @omer-musa-battal. Happy to help. :smile: 

> I generally try to avoid manual configurations in order to simplify reproducibility, that is why I would prefer the conda method over the manual method, if possible.

I would also like to understand why its not working. There may be a bug somewhere and other people may be experiencing the same problem but not raising and issue.

Two things are a concern:

Firstly, running
```
. /home/battal/all/sw/utils/mambaforge/share/bash-completion/completions/mamba
```
should 100% have got completion working, provided `/home/battal/all/sw/utils/mambaforge/share/bash-completion/bash_completion` has been loaded. Perhaps that is not the case?

Second, putting completion files in ` ~/.local/share/bash-completion/completions/` should 100% work on modern Linux systems with and up-to-date version of bash-completion (version > 2.0) installed system wide.

I'll have a think about how we can debug this.  BTW my timezone is Melbourne/Australia (GMT+11). If we could coordinate times that we are working on this we might be able to get to an answer much more quickly.

**Comment by tartansandal** [comment]
One approach you might consider, @omer-musa-battal, is creating a new user (say, `buttal-test`), log in as that user (`sudo su -l buttal-test`) and perform the standard installation method under their home directory. Once you have completion working there, you can directly compare the two setups. My suspicion is that there is something in your setup that is interfering with things. Checking and comparing the environment with `env` under each user may provide some insight.

**Comment by omer-musa-battal** [comment]
As it turns out, the issue was caused by me, the user. Let me elaborate.

`.bashrc` file on a fresh Ubuntu 20.04 installation, and after `conda init`, has the following content:
```
# ... Previous content omitted for brevity ...

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/battal/all/sw/utils/mambaforge/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/battal/all/sw/utils/mambaforge/etc/profile.d/conda.sh" ]; then
        . "/home/battal/all/sw/utils/mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/home/battal/all/sw/utils/mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/battal/all/sw/utils/mambaforge/etc/profile.d/mamba.sh" ]; then
    . "/home/battal/all/sw/utils/mambaforge/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<
```

Note the location of `.bash_aliases` here. It turns out that this file is sourced before `bash-completion` and `conda` is initialized!
I have read somewhere before about not editing the `.bashrc` file directly on Ubuntu systems anymore, but to edit the `.bash_aliases` file instead for shell initialization customizations. Therefore, I have put the following lines in `.bash_aliases` as well:
```
CONDA_ROOT="/home/battal/all/sw/utils/mambaforge"   # <- set to your Anaconda/Miniconda installation directory
if [[ -r "${CONDA_ROOT}/etc/profile.d/bash_completion.sh" ]]; then
    source "${CONDA_ROOT}/etc/profile.d/bash_completion.sh"
else
    echo "WARNING: could not find conda-bash-completion setup script"
fi
```
However, due to the order of sourcing in the default `.bashrc`, this approach fails. When I added the above snippet to my actual `.bashrc` file, under the `conda init` sequence, `mamba` bash completion worked flawlessly. It is my mistake to not follow the installation guide precisely.

**Comment by omer-musa-battal** [comment]
Thanks a lot @tartansandal, and sorry about the inconvenience.

Before closing the issue, I wanted to make some suggestions.

Could we perhaps modify the content of `${CONDA_ROOT}/etc/profile.d/bash_completion.sh` file like follows:

```
# shellcheck shell=sh disable=SC1091,SC2039,SC2166
# Check for interactive bash and that we haven't already been sourced.
if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x -a "x${CONDA_BASH_COMPLETION_LOADED-}" = x ]; then

    # Check for recent enough version of bash.
    if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
        [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
        [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
        if shopt -q progcomp && [ -r /home/battal/all/sw/utils/mambaforge/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /home/battal/all/sw/utils/mambaforge/share/bash-completion/bash_completion
            . /home/battal/all/sw/utils/mambaforge/share/bash-completion/completions/mamba  # added by battal
        fi
    fi

fi
```

When I did this in my setup, bash completion worked with `.bash_aliases` modifications as well, even after I reverted my changes in `.bashrc` file.
I do not know if this will cause problems for other people with different setups though, so I would like to take your feedback.

Again, thanks for your help throughout this issue.

**Comment by tartansandal** [comment]
Hi @omer-musa-battal. Glad you managed to get this sorted out. :smile:  I'll definitely add a comment to the installation instructions highlighting that the custom block needs to go both after the the "conda" initialization block __and__ after any system-wide bash completion code initialization.

The key point here is understanding that the "system" bash-completion (installed under  `/usr/share`) and "conda" bash-completion (installed under `$CONDA_ROOT/share`) have to peacefully co-exist and not get in each others way. This is easy if you have a base environment loaded. Its much harder if you don't - you have to take care to understand the loading process fully. 

This is doubly complicated by the way that bash-completion lazy loads the completion functions. If you look under `/usr/share/bash-completion/completions` you will see over 1000 completion scripts. You would not want to load all of these into every bash session as it would slow the shell down considerably, so the code uses some magic to load the completion functions the first time you try to use them (by doing `mamba <tab>`). If you do that for `mamba` while the "system" bash-completion is controlling things, then you will get a basic completion setup for an unknown command (just completes for file names). If you do that for `mamba` while the  "conda" bash-completion is controlling things, then the `mamba` command completion functions are loaded, which in turn loads the `conda` command completion functions, and gives you the full completion functionality.

Of course, on a modern Linux system (like Ubuntu 20) with a modern bash and a modern system-wide bash-completion installed and configured properly, you can side step all this by copying the command completion code (for both `mamba` and `conda`) into  the `~/.local/share/bash-completions` directory. In that case the system-wide bash-completion will take care of the lazy loading.

If you are interested, checkout https://github.com/tartansandal/bash-completion-feedstock/tree/master/recipe for all the gory details and the various patches I had to make to bash-completion to get this to work.

Anyway, since this seems to have been sorted out I'm going to close this ticket for now. Please feel free to reopen it or create a new one if you have any further issues. :smile:
